// <auto-generated />
using System;
using CafeUygulamasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeUygulamasi.Migrations
{
    [DbContext(typeof(CafeDbContext))]
    [Migration("20260209235900_AddContactInfoAndBranchOwned")]
    partial class AddContactInfoAndBranchOwned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CafeUygulamasi.Models.Branch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.OwnsOne("CafeUygulamasi.Models.BranchLocation", "Location", b1 =>
                        {
                            b1.Property<string>("BranchId")
                                .HasColumnType("varchar(255)");

                            b1.Property<decimal>("Lat")
                                .HasColumnType("decimal(65,30)")
                                .HasColumnName("Location_Lat");

                            b1.Property<decimal>("Lon")
                                .HasColumnType("decimal(65,30)")
                                .HasColumnName("Location_Lon");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("CafeUygulamasi.Models.BranchOrderLinks", "OrderLinks", b1 =>
                        {
                            b1.Property<string>("BranchId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Getir")
                                .HasColumnType("longtext")
                                .HasColumnName("OrderLinks_Getir");

                            b1.Property<string>("TrendyolYemek")
                                .HasColumnType("longtext")
                                .HasColumnName("OrderLinks_TrendyolYemek");

                            b1.Property<string>("Yemeksepeti")
                                .HasColumnType("longtext")
                                .HasColumnName("OrderLinks_Yemeksepeti");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsMany("CafeUygulamasi.Models.BranchWorkingHour", "WorkingHours", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("BranchId")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Close")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Open")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchWorkingHours");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Location");

                    b.Navigation("OrderLinks");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.ContactRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneOrEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.ContactInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Menu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Category", b =>
                {
                    b.HasOne("CafeUygulamasi.Models.Menu", "Menu")
                        .WithMany("Categories")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Product", b =>
                {
                    b.HasOne("CafeUygulamasi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.ContactInfo", b =>
                {
                    b.OwnsOne("CafeUygulamasi.Models.ContactSocial", "Social", b1 =>
                        {
                            b1.Property<string>("ContactInfoId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Facebook")
                                .HasColumnType("longtext")
                                .HasColumnName("Social_Facebook");

                            b1.Property<string>("Instagram")
                                .HasColumnType("longtext")
                                .HasColumnName("Social_Instagram");

                            b1.Property<string>("Tiktok")
                                .HasColumnType("longtext")
                                .HasColumnName("Social_Tiktok");

                            b1.Property<string>("Twitter")
                                .HasColumnType("longtext")
                                .HasColumnName("Social_Twitter");

                            b1.Property<string>("Whatsapp")
                                .HasColumnType("longtext")
                                .HasColumnName("Social_Whatsapp");

                            b1.HasKey("ContactInfoId");

                            b1.ToTable("ContactInfos");

                            b1.WithOwner()
                                .HasForeignKey("ContactInfoId");
                        });

                    b.Navigation("Social");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Menu", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
