// <auto-generated />
using System;
using CafeUygulamasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeUygulamasi.Migrations
{
    [DbContext(typeof(CafeDbContext))]
    [Migration("20260210184040_AddUsersWithRoles")]
    partial class AddUsersWithRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CafeUygulamasi.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Branch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.ContactInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.ContactRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneOrEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Menu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Branch", b =>
                {
                    b.OwnsOne("CafeUygulamasi.Models.BranchLocation", "Location", b1 =>
                        {
                            b1.Property<string>("BranchId")
                                .HasColumnType("varchar(255)");

                            b1.Property<decimal>("Lat")
                                .HasColumnType("decimal(65,30)");

                            b1.Property<decimal>("Lon")
                                .HasColumnType("decimal(65,30)");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsOne("CafeUygulamasi.Models.BranchOrderLinks", "OrderLinks", b1 =>
                        {
                            b1.Property<string>("BranchId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Getir")
                                .HasColumnType("longtext");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("tinyint(1)");

                            b1.Property<string>("TrendyolYemek")
                                .HasColumnType("longtext");

                            b1.Property<string>("Yemeksepeti")
                                .HasColumnType("longtext");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsMany("CafeUygulamasi.Models.BranchWorkingHour", "WorkingHours", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("BranchId")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Close")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Open")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchWorkingHours", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.Navigation("Location");

                    b.Navigation("OrderLinks")
                        .IsRequired();

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Category", b =>
                {
                    b.HasOne("CafeUygulamasi.Models.Menu", "Menu")
                        .WithMany("Categories")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.ContactInfo", b =>
                {
                    b.OwnsOne("CafeUygulamasi.Models.ContactOrderLinks", "OrderLinks", b1 =>
                        {
                            b1.Property<string>("ContactInfoId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Getir")
                                .HasColumnType("longtext");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("tinyint(1)");

                            b1.Property<string>("TrendyolYemek")
                                .HasColumnType("longtext");

                            b1.Property<string>("Yemeksepeti")
                                .HasColumnType("longtext");

                            b1.HasKey("ContactInfoId");

                            b1.ToTable("ContactInfos");

                            b1.WithOwner()
                                .HasForeignKey("ContactInfoId");
                        });

                    b.OwnsOne("CafeUygulamasi.Models.ContactSocial", "Social", b1 =>
                        {
                            b1.Property<string>("ContactInfoId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Facebook")
                                .HasColumnType("longtext");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("tinyint(1)");

                            b1.Property<string>("Instagram")
                                .HasColumnType("longtext");

                            b1.Property<string>("Tiktok")
                                .HasColumnType("longtext");

                            b1.Property<string>("Whatsapp")
                                .HasColumnType("longtext");

                            b1.Property<string>("X")
                                .HasColumnType("longtext");

                            b1.HasKey("ContactInfoId");

                            b1.ToTable("ContactInfos");

                            b1.WithOwner()
                                .HasForeignKey("ContactInfoId");
                        });

                    b.Navigation("OrderLinks")
                        .IsRequired();

                    b.Navigation("Social")
                        .IsRequired();
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Product", b =>
                {
                    b.HasOne("CafeUygulamasi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CafeUygulamasi.Models.ProductNutrition", "Nutrition", b1 =>
                        {
                            b1.Property<string>("ProductId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Allergens")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int?>("CaloriesKcal")
                                .HasColumnType("int");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("tinyint(1)");

                            b1.Property<string>("ServingSize")
                                .HasColumnType("longtext");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("CafeUygulamasi.Models.ProductMacros", "Macros", b2 =>
                                {
                                    b2.Property<string>("ProductNutritionProductId")
                                        .HasColumnType("varchar(255)");

                                    b2.Property<decimal?>("CarbsG")
                                        .HasColumnType("decimal(65,30)");

                                    b2.Property<decimal?>("FatG")
                                        .HasColumnType("decimal(65,30)");

                                    b2.Property<bool>("HasValue")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<decimal?>("ProteinG")
                                        .HasColumnType("decimal(65,30)");

                                    b2.HasKey("ProductNutritionProductId");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductNutritionProductId");
                                });

                            b1.OwnsOne("CafeUygulamasi.Models.ProductNutritionDetails", "Details", b2 =>
                                {
                                    b2.Property<string>("ProductNutritionProductId")
                                        .HasColumnType("varchar(255)");

                                    b2.Property<int?>("EnergyKj")
                                        .HasColumnType("int");

                                    b2.Property<decimal?>("FiberG")
                                        .HasColumnType("decimal(65,30)");

                                    b2.Property<bool>("HasValue")
                                        .HasColumnType("tinyint(1)");

                                    b2.Property<decimal?>("SodiumMg")
                                        .HasColumnType("decimal(65,30)");

                                    b2.Property<decimal?>("SugarG")
                                        .HasColumnType("decimal(65,30)");

                                    b2.HasKey("ProductNutritionProductId");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductNutritionProductId");
                                });

                            b1.Navigation("Details")
                                .IsRequired();

                            b1.Navigation("Macros")
                                .IsRequired();
                        });

                    b.Navigation("Category");

                    b.Navigation("Nutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CafeUygulamasi.Models.Menu", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
